[ADD] web: migration to 12.0
Vauxoo/web pull request #22
Opened 2019-04-13 01:27 UTC by frahikLV

2019-04-15 14:53 UTC, frahikLV commented
@keylor2906 can you review this?

2019-04-15 15:03 UTC, keylor2906 requested changes

2019-04-15 15:03 UTC, keylor2906 commented on web_widget_json_graph/static/src/js/web_widget_json_graph.js
> +});
Missing new line at EOF

2019-04-15 15:03 UTC, keylor2906 commented on web_widget_json_graph/static/src/scss/web_widget_json_graph.scss
> +}
Missing new line at EOF

2019-04-15 15:03 UTC, keylor2906 commented on web_widget_json_graph/static/data.tsv
> +24-Apr-07	93.24
Missing new line at EOF

2019-04-15 15:03 UTC, keylor2906 commented on web_widget_json_graph/views/templates.xml
> +<openerp>
This must be odoo tags, not openerp

2019-04-15 15:03 UTC, keylor2906 commented on web_widget_json_graph/views/templates.xml
> +    <data>
Remove this old data tags

2019-04-22 15:13 UTC, frahikLV commented
@keylor2906 done 👍

2019-04-22 15:28 UTC, keylor2906 requested changes

2019-04-22 15:28 UTC, keylor2906 commented on web_widget_json_graph/views/templates.xml
> +            <link rel="stylesheet" type="text/less" href="/web_widget_json_graph/static/src/less/web_widget_json_graph.less"/>
@frahikLV Please change this link, the less file was changed for a scss

2019-04-23 14:51 UTC, frahikLV commented
@keylor2906 Done 👍

2019-04-23 15:12 UTC, keylor2906 commented
@frahikLV please create a dummy instance with the forecast module to functionally test it

2020-01-06 16:09 UTC, frahikLV commented
@tomeyro This MR is required by the module, it is pending to merge, its functionality can be seen in the video https://youtu.be/zx7G9S-DUS8

c/c @keylor2906

2020-01-06 18:06 UTC, keylor2906 commented
@tomeyro It LGTM

2020-01-06 18:29 UTC, merged