[IMP] web_widget_x2many_graph: This module now can be used on 10.0 task#9512
Vauxoo/web pull request #9
Opened 2017-11-02 01:53 UTC by keylor2906

Using JSON instead of One2ManyField and it works smoothly without problem and more dynamic
Using less instead of css to look better

Examples:
![image](https://user-images.githubusercontent.com/17324113/32305976-3a7a01b8-bf3e-11e7-90e8-3d4d5f3d8003.png)
![image](https://user-images.githubusercontent.com/17324113/32305978-3e98b12c-bf3e-11e7-8ba2-4190a92664c3.png)
![image](https://user-images.githubusercontent.com/17324113/32305986-4992cc7a-bf3e-11e7-8541-76973e79546c.png)

2017-11-02 02:28 UTC, nhomar commented on web_widget_x2many_graph/static/src/js/web_widget_x2many_graph.js
> +    var FieldX2ManyGraphWidget = form_common.AbstractField.extend(form_common.ReinitializeFieldMixin, {
Call it json-graph or something like that due to the refactor this is not anymore a X2MAnyGraph

2017-11-02 02:29 UTC, nhomar commented on web_widget_x2many_graph/static/src/js/web_widget_x2many_graph.js
> +});
EOL fix please.

2017-11-02 02:30 UTC, nhomar commented on web_widget_x2many_graph/static/src/less/web_widget_x2many_graph.less
> +.oe_form_field_x2many_graph {
rename and re-document the way it works.

no more references to x2many

2017-11-02 03:15 UTC, nhomar commented
I like what I see.

Just few fixes, we refactor deeper on V11.0

2017-11-03 20:17 UTC, josemoralesp approved these changes

2017-11-03 23:06 UTC, nhomar requested changes
You have lints problems yet related to your module, change them or ignore them explicitally please.

in the architecture I am agree on this approach.

2017-11-03 23:06 UTC, nhomar commented on web_widget_json_graph/static/src/js/web_widget_json_graph.js
> +//############################################################################
User shorter licence please.

2017-11-04 01:41 UTC, nhomar approved these changes

2017-11-04 01:44 UTC, merged